#!/bin/bash


cd /etc/yum.repos.d/
wget https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
yum clean all && yum mackcache
yum -y install docker-ce
systemctl enable docker --now
systemctl status docker




#echo "start install docker-compose"
yum -y install epel-release  > /dev/null
yum -y install python-pip    > /dev/null

#echo "update pip"
pip install --upgrade pip  && pip install docker-compose

#echo "cat docker-compose version"
docker-compose --version



#############docker-compose###############################




version: '2.2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    container_name: kibana73
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - es73net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    container_name: es73
    environment:
      - cluster.name=geektime
      - node.name=es73
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es73
      - cluster.initial_master_nodes=es73
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es73data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es73net


volumes:
  es73data1:
    driver: local

networks:
  es73net:
    driver: bridge






	
